CREATE TABLE dbo.Categories(
ID INT PRIMARY KEY IDENTITY NOT NULL,
CategoryName NVARCHAR(MAX) NOT NULL);

CREATE TABLE dbo.Suppliers(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Name NVARCHAR(MAX) NOT NULL,
Phone NVARCHAR(MAX) NOT NULL,
Address NVARCHAR(MAX) NOT NULL);

CREATE TABLE dbo.Users(
ID INT PRIMARY KEY IDENTITY NOT NULL,
UserName NVARCHAR(MAX) NOT NULL,
Login NVARCHAR(MAX) NOT NULL,
Password NVARCHAR(MAX) NOT NULL,
Access INT NOT NULL);

CREATE TABLE dbo.Products(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Date DATETIME NOT NULL,
ProductName NVARCHAR(MAX) NOT NULL,
PriceIn FLOAT NOT NULL,
Count FLOAT NOT NULL,
Unit NVARCHAR(MAX) NOT NULL,
PriceOut FLOAT NOT NULL,
Summa FLOAT NOT NULL,
CategoryID INT FOREIGN KEY REFERENCES Categories(ID) NOT NULL,
SupplierID INT FOREIGN KEY REFERENCES Suppliers(ID) NOT NULL,
UserID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
Note NVARCHAR(MAX) NOT NULL);

CREATE TABLE dbo.SaleProducts(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Date DATETIME NOT NULL,
ProductName NVARCHAR(MAX) NOT NULL,
PriceIn FLOAT NOT NULL,
Count FLOAT NOT NULL,
Unit NVARCHAR(MAX) NOT NULL,
PriceOut FLOAT NOT NULL,
Summa FLOAT NOT NULL,
CategoryID INT FOREIGN KEY REFERENCES Categories(ID) NOT NULL,
SupplierID INT FOREIGN KEY REFERENCES Suppliers(ID) NOT NULL,
UserID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
Note NVARCHAR(MAX) NOT NULL);

CREATE TABLE dbo.UtilProducts(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Date DATETIME NOT NULL,
ProductName NVARCHAR(MAX) NOT NULL,
PriceIn FLOAT NOT NULL,
Count FLOAT NOT NULL,
Unit NVARCHAR(MAX) NOT NULL,
PriceOut FLOAT NOT NULL,
Summa FLOAT NOT NULL,
CategoryID INT FOREIGN KEY REFERENCES Categories(ID) NOT NULL,
SupplierID INT FOREIGN KEY REFERENCES Suppliers(ID) NOT NULL,
UserID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
Note NVARCHAR(MAX) NOT NULL);

DROP TABLE dbo.Products
DROP TABLE dbo.SaleProducts
DROP TABLE dbo.UtilProducts
DROP TABLE dbo.Categories
DROP TABLE dbo.Suppliers
DROP TABLE dbo.Users
